version: '3.8'

services:
  django:
    build:
      context: ./task1
      dockerfile: Dockerfile
    container_name: django
    command: bash -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
  
  fastapi: 
    build: 
      context: ./task2
      dockerfile: Dockerfile
    container_name: fastapi
    volumes:
      - .:/app
    ports: 
      - "5000:5000"