# Generated by Django 4.0.2 on 2022-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=50)),
                ('mobile_no', models.BigIntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('year', models.DateField()),
                ('about', models.TextField()),
                ('profile_pic', models.ImageField(upload_to='')),
                ('tech_subs', models.CharField(max_length=100)),
                ('address', models.TextField()),
                ('lang_spoken', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_organization', models.BooleanField(default=False)),
                ('is_individual', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateField(auto_now=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'UserDetail',
            },
        ),
    ]
