# Generated by Django 4.0.2 on 2022-02-26 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_alter_user_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_individual',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_organization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
