# Generated by Django 3.2.3 on 2022-03-02 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0004_remove_user_lang_spoken_remove_user_tech_subs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.DateField(blank=True),
        ),
    ]
