# Generated by Django 3.2.3 on 2022-03-02 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0005_alter_user_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='year',
            field=models.DateField(blank=True, null=True),
        ),
    ]
